name: example
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing the example app
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Import the local package
  llm_chat_ui:
    path: ../ # Relative path to the root of your `llm_chat_ui` package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
